[tool.poetry]
name = "ycc-hull"
version = "0.1.0"
description = "YCC Hull Back-End Service"
authors = ["Lajos Cseppentő <1053931+LajosCseppento@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.11"
# REST API
fastapi = "^0.86.0"
python-multipart = "^0.0.5"
uvicorn = { extras = ["standard"], version = "^0.19.0" }
# DB
cx-Oracle = "^8.3.0"
SQLAlchemy = "^1.4.43"
# Util
passlib = "^1.7.4"

[tool.poetry.dev-dependencies]
black = "^22.10.0"
Faker = "^15.3.1"
flake8 = "^5.0.4"
mypy = "^0.990"
poetryup = "^0.12.3"
pylint = "^2.15.5"
pytest = "^7.2.0"
pytest-cov = "^4.0.0"
pytest-html = "^3.2.0"
pytest-mock = "^3.10.0"
sqlacodegen = "^3.0.0rc1"

[tool.poetry.scripts]
start = "ycc_hull.main:start"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
