[tool.poetry]
name = "ycc-hull-generated-entities"
version = "0.0.0"
description = "YCC Hull Backend Service - Generated Entities"
authors = ["Lajos Cseppentő <1053931+LajosCseppento@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "~3.11"
# oracledb is not supported yet with SQLAlchemy 1.x
cx-Oracle = "^8.3.0"
SQLAlchemy = "^1.4.51"

[tool.poetry.dev-dependencies]
sqlacodegen = "^3.0.0rc3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
