name: CI
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    # Avoid duplicated CI
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Set Up Poetry
        uses: abatilo/actions-poetry@v2
      - name: Install
        run: poetry install
      - name: Build
        run: poetry build
      - name: Run test data generator
        run: |
          poetry run regenerate-test-data
          git status
      - name: Test
        run: poetry run pytest --cov=ycc_hull --cov-branch
      - name: Quick Lint
        run: |
          set -x
          poetry run black .
          git status
          poetry run mypy .
          poetry run flake8 .
          set +x
      - name: Pylint
        run: |
          set -x
          poetry run pylint --jobs 0 legacy_password_hashing load_tests test_data tests ycc_hull
          set +x
