name: CI
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    # Avoid duplicated CI
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"
      - name: Set up uv
        uses: astral-sh/setup-uv@v7
      - name: Init
        run: make init
      - name: Build
        run: uv build
      - name: Run test data generator
        run: |
          make regenerate-test-data
          git status
      - name: Check
        run: make check
